### ISSUE TITLE
Generating all cases for an Enum

### ISSUE THREAD

**Issue by ghost** [vincent-pradeilles/swift-tips#2]
From your tutorial: https://github.com/vincent-pradeilles/swift-tips#generating-all-cases-for-an-enum
Since XCode 10,  You can use `CaseIterable` following to this tutorial instead of create a function by yourself: https://developer.apple.com/documentation/swift/caseiterable

Thanks for these good suggestions, many of them are really useful!

**Comment by vincent-pradeilles** [comment]
You're absolutely right, I've added a warning to let people know that this old implementation should no longer be used in production code.

Thank you for pointing it out!
